#ifndef SNC_NUMBERS_H
#define SNC_NUMBERS_H

enum {
	SNC_ROMAN_I = 1,
	SNC_ROMAN_V = 5,
	SNC_ROMAN_X = 10,
	SNC_ROMAN_L = 50,
	SNC_ROMAN_C = 100,
	SNC_ROMAN_D = 500,
	SNC_ROMAN_M = 1000
};

#endif /* SNC_NUMBERS_H */
